server:
  port: 8081
  error:
    include-message: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: furryfund
    url: jdbc:mysql://furryfund.mysql.database.azure.com/furryfund
    password: giabao000@
  jpa:
    hibernate:
      ddl-auto: validate
      # kiểm tra schema để đảm bảo các entity match vs các cột trong db
      # nếu không match sẽ nhảy lỗi
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: nghihvdse182563@fpt.edu.vn
    password: qqhs ikcu grnb zlqx  # Sử dụng mật khẩu ứng dụng nếu bật 2FA
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./images/
# Thêm cấu hình Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: org.example.furryfriendfund.controllers # Thay thế bằng package chứa các controller của bạn
  default-produces-media-type: application/json
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE




